server:
  port: 9000
spring:
  application:
    name: card
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: ''
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  config:
    import:
      - application_prod.yaml
      - application_qa.yaml
card:
  message: 'Welcome to EazyBank Card api'
  contactDetails:
    name: 'John Doe support'
    email: 'p3sQc@example.com'
  onCallSupport:
    - (0555) 555 55 55
    - (044) 444 44 44