services:
  rabbitmq:
    image: rabbitmq:3.13-management
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 5s
    extends:
      file: common-config.yaml
      service: network-deploy-service

  configserver:
    image: "sharanggupta/configserver:2.0.0"
    container_name: configserver-ms
    ports:
      - "8071:8071"
    depends_on:
      rabbitmq:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent localhost:8071/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yaml
      service: microservice-base-config

  account:
    image: "sharanggupta/account:2.0.0"
    container_name: account-ms
    ports:
      - "8080:8080"
    environment:
      SPRING_APPLICATION_NAME: account
    extends:
      file: common-config.yaml
      service: microservice-configserver-config
    depends_on:
      configserver:
        condition: service_healthy

  loan:
    image: "sharanggupta/loan:2.0.0"
    container_name: loan-ms
    ports:
      - "8090:8090"
    environment:
      SPRING_APPLICATION_NAME: loan
    extends:
      file: common-config.yaml
      service: microservice-configserver-config
    depends_on:
      configserver:
        condition: service_healthy

  card:
    image: "sharanggupta/card:2.0.0"
    container_name: card-ms
    ports:
      - "9000:9000"
    environment:
      SPRING_APPLICATION_NAME: card
    extends:
      file: common-config.yaml
      service: microservice-configserver-config
    depends_on:
      configserver:
        condition: service_healthy

networks:
  eazybank:
    driver: "bridge"
