services:
  accountsdb:
    container_name: accountsdb
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: accountsdb
    extends:
      file: common-config.yaml
      service: microservice-db-config

  loansdb:
    container_name: loansdb
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: loansdb
    extends:
      file: common-config.yaml
      service: microservice-db-config

  cardsdb:
    container_name: cardsdb
    ports:
      - 3308:3306
    environment:
      MYSQL_DATABASE: cardsdb
    extends:
      file: common-config.yaml
      service: microservice-db-config

  rabbitmq:
    image: rabbitmq:3.13-management
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 5s
    extends:
      file: common-config.yaml
      service: network-deploy-service

  configserver:
    image: "sharanggupta/configserver:4.0.0"
    container_name: configserver-ms
    ports:
      - "8071:8071"
    depends_on:
      rabbitmq:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent localhost:8071/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yaml
      service: microservice-base-config

  eurekaserver:
    image: "sharanggupta/eurekaserver:4.0.0"
    container_name: eurekaserver-ms
    ports:
      - "8070:8070"
    depends_on:
      configserver:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent localhost:8070/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yaml
      service: microservice-configserver-config
    environment:
      SPRING_APPLICATION_NAME: eurekaserver

  account:
    image: "sharanggupta/account:4.0.0"
    container_name: account-ms
    ports:
      - "8080:8080"
    environment:
      SPRING_APPLICATION_NAME: account
      SPRING_DATASOURCE_URL: "jdbc:mysql://accountsdb:3306/accountsdb"
    extends:
      file: common-config.yaml
      service: microservice-eureka-config
    depends_on:
      accountsdb:
        condition: service_healthy
      configserver:
        condition: service_healthy

  loan:
    image: "sharanggupta/loan:4.0.0"
    container_name: loan-ms
    ports:
      - "8090:8090"
    environment:
      SPRING_APPLICATION_NAME: loan
      SPRING_DATASOURCE_URL: "jdbc:mysql://loansdb:3306/loansdb"
    extends:
      file: common-config.yaml
      service: microservice-eureka-config
    depends_on:
      loansdb:
        condition: service_healthy
      configserver:
        condition: service_healthy

  card:
    image: "sharanggupta/card:4.0.0"
    container_name: card-ms
    ports:
      - "9000:9000"
    environment:
      SPRING_APPLICATION_NAME: card
      SPRING_DATASOURCE_URL: "jdbc:mysql://cardsdb:3306/cardsdb"
    extends:
      file: common-config.yaml
      service: microservice-eureka-config
    depends_on:
      cardsdb:
        condition: service_healthy
      configserver:
        condition: service_healthy

networks:
  eazybank:
    driver: "bridge"
