spring:
  application:
    name: "configserver"

  profiles:
#    active: native
    active: git

#use the absolute file path as shown in the commented line (14) as an alternative
  cloud:
    config:
      server:
        git:
          uri: https://github.com/sharang1996/eazybank-config
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true
#        native:
#          search-locations: "classpath:/config"
#          search-locations: "file:///Users/sharang/Code/eazybank/configserver/src/main/resources/config"

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

encrypt:
  # Would ideally be set as an environment variable
  key: "B4uSHh4rsFl690FP"

server:
  port: 8071

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      probes:
        enabled: true